spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/releaseLearning?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 0613lbc0613
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      request-size: 10MB
  web:
    resources:
      static-locations: classpath:/
server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: webrtc
    keyStoreType: PKCS12
    keyAlias: webrtc
